name: Build MakeRW

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86_64, arm, armhf, aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf

      - name: Build MakeRW
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            export CROSS_COMPILE=""
          elif [ "${{ matrix.arch }}" = "armhf" ]; then
            export CROSS_COMPILE="arm-linux-gnueabihf-"
          elif [ "${{ matrix.arch }}" = "arm" ]; then
            export CROSS_COMPILE="arm-linux-gnueabi-"
          elif [ "${{ matrix.arch }}" = "aarch64" ]; then
            export CROSS_COMPILE="aarch64-linux-gnu-"
          fi

          export STATIC=1

          make clean
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: makerw-${{ matrix.arch }}${{ matrix.static == 1 && '-static' || '' }}
          path: makerw
